trigger:
- master
- develop

resources:
  repositories:
    - repository: templates
      type: git
      name: StarkBIM.Build/StarkBIM.Build
      ref: refs/tags/0.2.71+gcf6587c3ea

jobs:
- template: Azure/azure-pipelines.yml@templates  # Template reference
  parameters:
    publishNuGet: 'true'